
// LOGIN
export const INITIAL_LOGIN = 'INITIAL_LOGIN';
export const BEGIN_LOGIN = 'BEGIN_LOGIN';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_ERROR = 'LOGIN_ERROR';
export const UPDATE_DATA_LOGIN = 'UPDATE_DATA_LOGIN';
export const GOT_DATA_LOGIN = 'GOT_DATA_LOGIN';
export const LOGOUT = 'LOGOUT';
export const LOGIN  = 'LOGIN';
//Register
export const BEGIN_REGISTER = "BEGIN_REGISTER";
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_ERROR = 'REGISTER_ERROR';
// news
export const BEGIN_GET_NEWS = "BEGIN_GET_NEWS"
export const GET_NEWS_SUCCESS = 'GET_NEWS_SUCCESS';
export const GET_NEWS_ERROR = "GET_NEWS_ERROR";

// detail of new
export const BEGIN_GET_DETAIL_NEW = "BEGIN_GET_DETAIL_NEW";
export const GET_DETAIL_NEW_SUCCESS = "GET_DETAIL_NEW_SUCCESS";
export const GET_DETAIL_NEW_ERROR  = "GET_DETAIL_NEW_ERROR";

// reservation
export const BEGIN_GET_RESERVATION = "BEGIN_GET_RESERVATION";
export const GET_REVERVATION_SUCCESS = "GET_REVERVATION_SUCCESS";
export const GET_REVERVATION_ERROR = "GET_REVERVATION_ERROR";

// place of reservation
export const BEGIN_GET_PROVINCES = "BEGIN_GET_PROVINCES";
export const GET_PROVINCES_SUCCESS = "GET_PROVINCES_SUCCESS";
export const GET_PROVINCES_ERROR = "GET_PROVINCES_ERROR";

// search news
export const BEGIN_SEARCH_NEW = "BEGIN_SEARCH_NEW";
export const GET_SEARCH_NEW_SUCCESS = "GET_SEARCH_NEW_SUCCESS";
export const GET_SEARCH_NEW_ERROR = "GET_SEARCH_NEW_ERROR";
// get More News
export const BEGIN_GET_MORE_NEWS = "BEGIN_GET_MORE_NEWS";
export const GET_MORE_NEWS_SUCCESS = "GET_MORE_NEWS_SUCCESS";
export const GET_MORE_NEWS_ERROR  = "GET_MORE_NEWS_ERROR";
// refresh New
export const BEGIN_REFRESH_NEWS = "BEGIN_REFRESH_NEWS";
export const GET_REFRESH_SUCCESS = "GET_REFRESH_SUCCESS";
export const GET_REFRESH_ERROR = "GET_REFRESH_ERROR";
// get More News When Search
export const BEGIN_MORE_NEWS_SEARCH = "BEGIN_MORE_NEW_SEARCH";
export const GET_MORE_NEWS_SEARCH_SUCCESS = "GET_MORE_NEWS_SEARCH_SUCCESS";
export const GET_MORE_NEWS_SEARCH_ERROR  = "GET_MORE_NEWS_SEARCH_ERROR";

//search base
export const BEGIN_SEARCH_BASES = "BEGIN_SEARCH_BASES";
export const GET_SEARCH_BASES_SUCCESS = "GET_SEARCH_BASES_SUCCESS";
export const GET_SEARCH_BASES_ERROR   = "GET_SEARCH_BASES_ERROR";
//get user_packs

export const BEGIN_GET_USER_PACKS = "BEGIN_GET_USER_PACKS";
export const GET_USER_PACKS_SUCCESS = "GET_USER_PACKS_SUCCESS";
export const GET_USER_PACKS_ERROR   = "GET_USER_PACKS_ERROR";
//register user_packs
export const BEGIN_REGISTER_USER_PACK = "BEGIN_REGISTER_USER_PACK";
export const REGISTER_USER_PACK_SUCCESS = "REGISTER_USER_PACK_SUCCESS";
export const REGISTER_USER_PACK_ERROR   = "REGISTER_USER_PACK_ERROR";

//get Notification
export const BEGIN_GET_NOTIFICATION    = "BEGIN_GET_NOTIFICATION";
export const GET_NOTIFICATION_SUCCESS = "GET_NOTIFICATION_SUCCESS";
export const GET_NOTIFICATION_ERROR   = "GET_NOTIFICATION_ERROR";
