
// LOGIN
export const INITIAL_LOGIN = 'INITIAL_LOGIN';
export const BEGIN_LOGIN = 'BEGIN_LOGIN';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_ERROR = 'LOGIN_ERROR';
export const UPDATE_DATA_LOGIN = 'UPDATE_DATA_LOGIN';
export const GOT_DATA_LOGIN = 'GOT_DATA_LOGIN';
export const LOGOUT = 'LOGOUT';
export const LOGIN  = 'LOGIN';
//Register
export const BEGIN_REGISTER = "BEGIN_REGISTER";
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_ERROR = 'REGISTER_ERROR';
// news
export const GET_NEWS = 'GET_NEWS';


// reservation
export const BEGIN_GET_RESERVATION = "BEGIN_GET_RESERVATION";
export const GET_REVERVATION_SUCCESS = "GET_REVERVATION_SUCCESS";
export const GET_REVERVATION_ERROR = "GET_REVERVATION_ERROR";

// place of reservation
export const BEGIN_GET_PROVINCES = "BEGIN_GET_PROVINCES";
export const GET_PROVINCES_SUCCESS = "GET_PROVINCES_SUCCESS";
export const GET_PROVINCES_ERROR = "GET_PROVINCES_ERROR";